Add implementation for mobile phones
ZimnitskiYury/itechart_css-container pull request #4
Opened 2021-05-03 11:05 UTC by ZimnitskiYury

2021-05-18 22:08 UTC, drodov requested changes

2021-05-18 22:08 UTC, drodov commented on index.html
> +            <h2 class="order__instruction-header">Как заказать</h2>
Keep only list items inside list container.

2021-05-18 22:08 UTC, drodov commented on index.html
> +                <article class="order__step-description">
It's not an appropriate tag.

2021-05-18 22:08 UTC, drodov commented on index.html
> +        <span class="contacts__annotation">Остались вопросы?</span>
Use `header` tag, please check other places.

2021-05-18 22:08 UTC, drodov commented on index.html
> +                    <a class="contact-info__phone-link" href="tel:+79068999296"><i class="fas fa-phone-alt"></i> +7 906 899 92 96 </a>
Do you need to use `i` tag?

2021-05-18 22:08 UTC, drodov commented on index.html
> +                <li class="contact-info__list-item">
All items look like separate blocks to me.

2021-05-18 22:08 UTC, drodov commented on index.html
> +                <h5 class="logo__text">Cakes</h5>
Let's discuss using a heading here.

2021-05-18 22:08 UTC, drodov commented on index.html
> +                <li class="nav-list__item"><a class="nav-list__link" href="#categories">Наши торты</a></li>
Do you need both classes here?

2021-05-18 22:08 UTC, drodov commented on index.html
> +        <div class="footer__credentials-tablet">
Please check how to name modifiers and use them,

2021-05-18 22:08 UTC, drodov commented on index.html
> +        <div class="footer__credentials-mobile">
Let's move device-specific classes to separate elements instead of the whole footer.

2021-05-24 22:45 UTC, ZimnitskiYury commented on index.html
> +                <h5 class="logo__text">Cakes</h5>
Replaced to <span>

2021-05-24 22:46 UTC, ZimnitskiYury commented on index.html
> +        <div class="footer__credentials-mobile">
Deleted

2021-05-24 23:44 UTC, ZimnitskiYury commented on index.html
> +                <li class="contact-info__list-item">
Fixed

2021-05-24 23:44 UTC, ZimnitskiYury commented on css/contacts/contact-info.css
> +    justify-content: flex-start;
Deleted

2021-05-24 23:45 UTC, ZimnitskiYury commented on css/contacts/contact-info.css
> +    background-size: 30px;
Combined

2021-05-25 03:25 UTC, ZimnitskiYury commented on css/about-us/about-us.css
> +        padding: 48px 6.25% 0 6.25%;
Fixed

2021-05-25 03:26 UTC, ZimnitskiYury commented on css/about-us/about-us.css
> +    }
Fixed everywhere. `line-height: auto;` deleted (wrong property)

2021-05-25 03:27 UTC, ZimnitskiYury commented on css/categories.css
> +}
fixed everywhere

2021-05-25 03:28 UTC, ZimnitskiYury commented on css/categories.css
> +    z-index: 1;
Image overlaps text

2021-05-25 03:28 UTC, ZimnitskiYury commented on css/categories.css
> +        align-self: flex-start;
Cleaned everywhere

2021-05-25 03:28 UTC, ZimnitskiYury commented on css/categories.css
> +        margin-left: -212px;
Fixed

2021-05-25 03:29 UTC, ZimnitskiYury commented on css/categories.css
> +    .categories__container-item:last-of-type {
Fixed

2021-05-25 03:29 UTC, ZimnitskiYury commented on css/contacts/contact-info.css
> +    font-size: 20px;
Fixed everywhere

2021-05-25 03:29 UTC, ZimnitskiYury commented on css/contacts/contact-info.css
> +        margin-bottom: 22px;
Duplicates removed

2021-05-25 03:29 UTC, ZimnitskiYury commented on css/footer/footer.css
> +footer {
Changed to class

2021-05-25 03:30 UTC, ZimnitskiYury commented on index.html
> +            <a href="./index.html" class="header__logo-link">Cakes</a>
fixed

2021-05-25 03:30 UTC, ZimnitskiYury commented on index.html
> +        <span class="main-page__annotation">Ручная работа</span>
Added header tag

2021-05-25 03:31 UTC, ZimnitskiYury commented on index.html
> +            <li class="categories__container-item">
Did

2021-05-25 03:32 UTC, ZimnitskiYury commented on index.html
> +                        <h2 class="dictum__user-info">юрист, 33 года</h2>
Fixed

2021-05-25 03:32 UTC, ZimnitskiYury commented on index.html
> +        <span class="our-comment__title">’’</span>
Did it with :before

2021-05-25 03:32 UTC, ZimnitskiYury commented on index.html
> +                <article class="our-advantages__advantage">
Fixed

2021-05-25 03:33 UTC, ZimnitskiYury commented on index.html
> +        <span class="contacts__annotation">Остались вопросы?</span>
Did

2021-06-22 09:29 UTC, merged